title: console.log("Hi")
author:
  name: imsykim1130
  email: imsykim1130@gmail.com
description:
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
data_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

contact:
  github: https://github.com/imsykim1130
  gmail: imsykim1130@gmail.com
